# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-18 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(db_index=True, default=False, verbose_name='Sent')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Sender')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-mail')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of birth')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.AddField(
            model_name='maillog',
            name='to_email',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Subscriber'),
        ),
    ]
